### ISSUE TITLE
test.yaml 

### ISSUE THREAD

**Issue by HHLiufighting** [preddy5/G3DR#2]
where is test.yaml？

**Comment by MontaEllis** [comment]
+1

**Comment by muses0229** [comment]
+1

**Comment by preddy5** [comment]
Thank you for your interest in G3DR, I have since left Huawei so I don't have access to the exact config file, but the only difference between the config file available in the repo and the inference config file is depth_resolution, depth_resolution_importance parameters are set to 64 during inference.
