### ISSUE TITLE
Where's the implementation for f_rgbd?

### ISSUE THREAD

**Issue by Michaelsqj** [preddy5/G3DR#3]
Hey, in your paper, f_rgbd is mentioned, but I couldn't find the implementation in your repo. And your readme only suggested predicting monocular depth on imagenet. So how's the f_rgbd involved in the whole process?

**Comment by preddy5** [comment]
Hey @Michaelsqj 
I appreciate your interest in our work.
F_rgbd outputs are the inputs to the model available in the repository we do this because generating RGBD images using a single network is more efficient than generating RGB images and then performing depth estimation separately. However, the pipeline will also work if this is done separately.

Unfortunately, the code I used for the f_rgbd diffusion part of the paper couldn't be released since it was used in a few product applications. You can train such a network using [dataset](https://drive.google.com/file/d/1dwvbVNkx7pkTeOBrss0AE-xYMfkRtAps/view?usp=drive_link) all the technical parts of the code are mostly based on the lucidrains denoising_diffusion_pytorch library.

For testing here are the images generated using the diffusion model. I hope this helps.
https://drive.google.com/file/d/1yVcIkKRFezZnc2k_TnXfHhaKpWDb_E3z/view?usp=sharing 

Regards,
Pradyumna.
